version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-macos:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      
      # Install Node.js using CircleCI orb
      - node/install:
          node-version: '18'
          
      # Create macOS icon
      - run:
          name: Create macOS Icon
          command: |
            if [ -f "public/logo.png" ] && [ ! -f "public/logo.icns" ]; then
              mkdir -p logo.iconset
              sips -z 512 512 public/logo.png --out logo.iconset/icon_512x512.png
              sips -z 1024 1024 public/logo.png --out logo.iconset/icon_512x512@2x.png
              iconutil -c icns logo.iconset -o public/logo.icns
              echo "✅ Created macOS icon"
            else
              echo "✅ Using existing icon or PNG fallback"
            fi
            
      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install
            
      # Build Next.js app
      - run:
          name: Build Next.js App
          command: npm run build
            
      # Build macOS installer
      - run:
          name: Build macOS Installer
          command: npm run dist-mac
            
      # Store artifacts
      - store_artifacts:
          path: dist
          destination: installers

workflows:
  build-and-deploy:
    jobs:
      - build-macos:
          filters:
            branches:
              only: main
